# Generated by Django 5.2.6 on 2025-10-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='min_delivery_time',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='min_price',
        ),
    ]
