# Generated by Django 5.2.6 on 2025-11-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_offers', '0002_remove_offer_min_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='delivery_time_in_days',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='price',
            field=models.IntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='revisions',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
