# Generated by Django 5.2.6 on 2025-11-12 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_offers', '0004_alter_offerdetail_delivery_time_in_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='delivery_time_in_days',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='revisions',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
