# Generated by Django 5.2.6 on 2025-11-14 10:10

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_offers', '0005_alter_offerdetail_delivery_time_in_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.overwrite_file_upload),
        ),
    ]
