# Generated by Django 5.2.6 on 2025-09-23 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='profile_pics/')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('tel', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('working_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, choices=[('customer', 'Customer'), ('business', 'Business')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
