# Generated by Django 5.2.6 on 2025-09-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='uploaded_at',
            new_name='file_uploaded_at',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='working_hours',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
