# Generated by Django 5.2.6 on 2025-11-14 10:10

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.overwrite_file_upload),
        ),
    ]
